name: Release Drafter Beta

on:
  push:
    branches:
      - BETA-TEST

  pull_request:
    types:
      - opened
      - reopened
      - synchronized

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout beta branch
        uses: actions/checkout@v4
        with:
          ref: BETA-TEST
          fetch-depth: 0

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v7
        with:
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
